### ISSUE TITLE
Disproportionality analysis

### ISSUE THREAD

**Issue by sooyoungsarah** [fusarolimichele/DiAna_package#13]
Hi, I was using the disproportionality_analysis function and was wondering if there could be a direct way to set the input as a list of "primaryid"s instead of automatically getting the drugnames from the system. Especially since the previous steps allowed you to review records of the drugs after retrieval. Thank you.

**Comment by fusarolimichele** [comment]
Dear sooyoungsarah,
Thank you for using DiAna and reaching out. I am not sure I have understood your request. A disproportionality analysis needs 4 numbers: the number of reports with the drug and the event (already inspected), but also the number of reports with the drug but other events, the number of reports with the event but other drugs, and the number of reports with other drugs and other events. For this reason just providing a list of primaryid would not work. Help me understand better what you mean and we will gladly help you!

**Comment by sooyoungsarah** [comment]
Thanks for the prompt response. I specifically want to provide the list of primaryids of the drug of interest.

**Comment by fusarolimichele** [comment]
> Thanks for the prompt response. I specifically want to provide the list of primaryids of the drug of interest.

Ok, and you would provide also the event as another list of primaryids or using PTs?

We already implemented something similar to what you are proposing when we calculated an event-event disproportionality analysis, to see which events are associated with drug-induced impulsivity (https://doi.org/10.1101/2023.11.17.23298635). In that case we provided a list of primaryids recording impulsivity to a variation of the disproportionality function. It should therefore not take much time to implement it for DiAna. We will work on it in the next month! I will write here as soon as it is available!

p.s. just out of curiosity and if you can say it. What would be your specific motivation for providing primaryids instead of the name of the substance? It could be interesting to add an example similar to yours to the upcoming tutorials.

**Comment by sooyoungsarah** [comment]
Thank you! I was filtering the raw data before getting to know this specific package and we filtered duplicates, some data with missing info etc. But the most important part is that we are curious about the difference in adverse events based on the route of administration.

**Comment by fusarolimichele** [comment]
Really interesting! I will tell you as soon as the new function is available

**Comment by sooyoungsarah** [comment]
I guess the disproportionality analysis will have to identify the primaryid and the drug sequence in this case!

**Comment by fusarolimichele** [comment]
Dear sooyoungsarah, we are still working on the function that allows to perform the disproportionality analysis on any two columns of the database. In the meantime, we included a new function that is called disproportionality_comparison. This function asks for the instances of the contingency table and automatically calculate frequentist (ROR,PRR,RRR) and Bayesian disproportionality analyses (IC, and IC gamma –different only in how the confidence interval is calculated). We thought this could be useful to solve the problem you have before the new function is implemented, can you confirm? Here an example. Please, reach out for anything!
<img width="632" alt="image" src="https://github.com/fusarolimichele/DiAna_package/assets/46229870/a29adcea-6b41-47cd-936b-274f3d58c1d8">

**Comment by sooyoungsarah** [comment]
Yes, it was very helpful. Thank you!!
